version: "3.9" # optional since v1.27.0

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/traefik:/etc/traefik
      - traefik-ssl-certs:/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik:/var/log/traefik
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-api.rule: "Host(`traefik.wps.3dconfiguration.com`)"
      traefik.http.routers.traefik-api.entryPoints: "web, websecure"
      traefik.http.routers.traefik-api.tls: "true"
      traefik.http.routers.traefik-api.tls.certresolver: "production"
      traefik.http.routers.traefik-api.service: "api@internal"
      traefik.http.routers.traefik-api.middlewares: "dashboardauth@docker"
      #basic auth
      traefik.http.middlewares.dashboardauth.basicauth.users: "admin:$$2y$$10$$YZLOYr0MQZ8co.C12CR09OAenp9F8nG5c1gVxW/EvWi5Yw5QKlK8S"
    networks:
      - traefik-proxy

  portainer:
    image: "portainer/portainer-ce:2.11.0"
    container_name: "portainer"
    restart: always
    depends_on:
      - traefik
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.rule: "Host(`portainer.wps.3dconfiguration.com`)"
      traefik.http.routers.portainer.entryPoints: "web, websecure"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.tls.certresolver: "production"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"

    networks:
      - traefik-proxy

volumes:
  traefik-ssl-certs:
    driver: local
  portainer_data:
    driver: local

networks:
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
